fs: verity: Added some more stuff trying to make it compilable.
Unfortunately I failed at this point:

fs/verity/open.c:202:2: error: implicit declaration of function 'arch_cmpxchg' [-Werror=implicit-function-declaration]
  if (cmpxchg_release(&inode->i_verity_info, NULL, vi) != NULL) {
  ^

Change-Id: I0c2c74fdcee0ecc8a3f93be472b52457322b66c7
(cherry picked from commit 93423729efdbb9b6884e2a2b625d6020595775d9)