scsi: ufs: fix compilation errors with gcc5 [port][3.18]
When compiling with gcc5, it throws below errors:

drivers/scsi/ufs/ufs-qcom.c: In function 'ufs_qcom_hce_enable_notify':
drivers/scsi/ufs/ufs-qcom.c:352:10: warning: switch condition has boolean
value [-Wswitch-bool] error, forbidden warning: ufs-qcom.c:352

This is because we are using the boolean value in switch condition and it
seems to be forbidden by compiler (by default). Fix this by using the
proper enum type instead of boolean.

Change-Id: Iee6950e5986dc51afbf9440cd4773b4d0f02fcdc
Signed-off-by: Subhash Jadavani <subhashj@codeaurora.org>
Git-commit: d095e31176f075ab99b1bf94fafe8d2f61481bb2
Signed-off-by: GreyLeshy <andreiskull@gmail.com>